### PR TITLE
Inherit params

### PR DESCRIPTION
**Pull request by isteves**
Only changed params...hopefully doesn't conflict with anything you've been doing, @amoeba!  

I started out using `@family` but I realized maybe we don't need it afterall since our naming convention autocompletes quite well?  Perhaps we could consider documenting several functions together with `@rdname` or `@describeIn` http://r-pkgs.had.co.nz/man.html#dry2

What do you think?

### CODE REVIEW

**Comment by amoeba** [comment]
Most excellent, thanks @isteves. I think `inheritParams` works quite nicely and interestingly here. I don't think I mind the non-DRY nature of having all the Roxgeyn docs typed out fully but I like the explicit nature of this usage of `inheritParams`. I'm all for it!

As for documenting several functions together, I recently ran into this in another package and it seemed like the big factor in whether to do this or not was how similar the arguments are. Our functions are pretty dang similar, yeah?, so maybe this would work great to `rdname` them and put them on the same page.

**Comment by amoeba** [comment]
Thanks for the PR. Looks good to me.

**Comment by isteves** [comment]
Hah well when you're copy and pasting roxygen to update a sentence, you start to feel it!  

Ok, that will be next on the to-do.  I think we have a few "create"/"edit" pairs that could definitely be grouped together.

**Comment by isteves** [comment]
Oh and forgot to link to the issue: #27

**Pull request merged**
